name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: projects-nexus/nexus_tweak@app-builder
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
